
CREATE TABLE Students(
    IDNR VARCHAR(10)                NOT NULL,
    NAME VARCHAR(20)                NOT NULL,
    LOGIN VARCHAR(6)                NOT NULL,
    PROGRAM VARCHAR(20)             NOT NULL,

    UNIQUE(IDNR),
    UNIQUE(LOGIN),

    PRIMARY KEY (IDNR)
);

CREATE TABLE Branches(
    NAME VARCHAR(20)                      ,
    PROGRAM VARCHAR(20)                   ,

    PRIMARY KEY (NAME,PROGRAM)

);

CREATE TABLE Courses(
    CODE VARCHAR(6)                       NOT NULL,
    NAME VARCHAR(20)         UNIQUE       NOT NULL,
    CREDITS REAL                           NOT NULL,
    DEPARTMENT VARCHAR(20)                NOT NULL,

    PRIMARY KEY (CODE)

);

CREATE TABLE LimitedCourses(
    CODE VARCHAR(6)        UNIQUE      NOT NULL,
    CAPACITY INT                       NOT NULL,

    PRIMARY KEY (CODE) ,

    FOREIGN KEY  (CODE) REFERENCES Courses(CODE)

);

CREATE TABLE StudentBranches(
    STUDENT VARCHAR(20)             NOT NULL,
    BRANCH VARCHAR(20)              NOT NULL,
    PROGRAM VARCHAR(20)             NOT NULL,

    PRIMARY KEY (STUDENT),

    FOREIGN KEY (STUDENT) REFERENCES Students(IDNR),
    FOREIGN KEY (BRANCH, PROGRAM) REFERENCES Branches(NAME, PROGRAM)

);

CREATE TABLE Classifications(
    NAME VARCHAR(20)               NOT NULL,

      PRIMARY KEY (NAME)
);

CREATE TABLE Classified(
    COURSE VARCHAR(20)             NOT NULL,
    CLASSIFICATION VARCHAR(20)     NOT NULL,

    PRIMARY KEY (COURSE, CLASSIFICATION),

    FOREIGN KEY (COURSE) REFERENCES Courses(CODE),
    FOREIGN KEY (CLASSIFICATION) REFERENCES Classifications(NAME)

);

CREATE TABLE MandatoryProgram(
    COURSE VARCHAR(20)            NOT NULL,
    PROGRAM VARCHAR(20)           NOT NULL,

    PRIMARY KEY (COURSE, PROGRAM),

    FOREIGN KEY (COURSE) REFERENCES Courses(CODE)

);

CREATE TABLE MandatoryBranch(
    COURSE VARCHAR(20)           NOT NULL,
    BRANCH VARCHAR(20)           NOT NULL,
    PROGRAM VARCHAR(20)          NOT NULL,

    PRIMARY KEY (COURSE, BRANCH, PROGRAM),

    FOREIGN KEY (COURSE) REFERENCES Courses(CODE),
    FOREIGN KEY  (BRANCH, PROGRAM) REFERENCES Branches(NAME, PROGRAM)

);

CREATE TABLE RecommendedBranch(
    COURSE VARCHAR(20)          NOT NULL,
    BRANCH VARCHAR(20)          NOT NULL,
    PROGRAM VARCHAR(20)         NOT NULL,

    PRIMARY KEY (COURSE, BRANCH, PROGRAM),

    FOREIGN KEY (COURSE) REFERENCES Courses(CODE),
    FOREIGN KEY (BRANCH, PROGRAM) REFERENCES Branches(NAME, PROGRAM)

);

CREATE TABLE Registered(
    STUDENT VARCHAR(20)        NOT NULL,
    COURSE VARCHAR(20)         NOT NULL,

    PRIMARY KEY (STUDENT, COURSE),

    FOREIGN KEY (STUDENT) REFERENCES Students(IDNR),
    FOREIGN KEY (COURSE) REFERENCES Courses(CODE)

);

CREATE TABLE Taken(
    STUDENT VARCHAR(20)        NOT NULL,
    COURSE VARCHAR(20)         NOT NULL,
    GRADE CHAR                 NOT NULL,

    CHECK( GRADE IN ( 'U' ,'3' ,'4' ,'5')),

    PRIMARY KEY (STUDENT, COURSE),

    FOREIGN KEY (STUDENT) REFERENCES Students(IDNR),
    FOREIGN KEY (COURSE) REFERENCES Courses(CODE)

);

CREATE TABLE WaitIngList(
    STUDENT VARCHAR(20)       NOT NULL,
    COURSE VARCHAR(20)       NOT NULL,
    POSITION SERIAL           NOT NULL,

    PRIMARY KEY (STUDENT, COURSE),

    FOREIGN KEY (STUDENT) REFERENCES Students(IDNR),
    FOREIGN KEY (COURSE) REFERENCES LimitedCourses(CODE)


);

